### ISSUE TITLE
Structure of the folders

### ISSUE THREAD

**Issue by Thuener** [schardong/thesisPUC-Template#2]
I have some questions about the structure of the folder. I can make a detailed explanation in the readme, but I will need your help @schardong .

- Why there is dsc and msc? What is the difference between then?

**Comment by schardong** [comment]
The phd, dsc and msc parameters change the author's degree: "Doctor in X", "Doctor of Science - X" or "Master in X", where X is the course. I noticed that some departments use the Doctor of Science (Informatics and Mathematics, for example), while others remove the "of Science" part, hence the phd/dsc division.

**Comment by Thuener** [comment]
The differences between then are just this? Maybe we can put this as a parameter, and the user defines this in .tex

**Comment by schardong** [comment]
Yes, thats basically it. The msc, phd and dsc words are class parameters of ThesisPUC.cls, actually. The folders were created more as an example, if I'm not mistaken. If you diff the main files of msc, dsc and phd folders, you'll see that the main difference is in the class parameters. See below an example of a diff between the thesis_dsc and thesis_msc main files.

![image](https://user-images.githubusercontent.com/1559139/95090467-b4836500-06fb-11eb-8deb-4943a6b69f09.png)

**Comment by Thuener** [comment]
Ok, great!!
Maybe the solution is to explain this in the ReadMe and in the .tex example.

**Comment by schardong** [comment]
Sure, I'll get to it this week.

**Comment by Thuener** [comment]
Wait. I have a branch here, I will send tomorrow.
